image: btmash/alpine-ssh-rsync:latest

stages:
  - production

deploy_production:
  stage: production
  script:
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -p22 $DEPLOY_URL "mkdir -p $SITE_DIR/releases/$CI_JOB_ID"
    - rsync -aq . $DEPLOY_URL:$SITE_DIR/releases/$CI_JOB_ID
    - ssh -p22 $DEPLOY_URL "ln -s $SITE_DIR/shared/.env $SITE_DIR/releases/$CI_JOB_ID/.env"
    - ssh -p22 $DEPLOY_URL "ln -s $SITE_DIR/shared/storage $SITE_DIR/releases/$CI_JOB_ID/storage"
    - ssh -p22 $DEPLOY_URL "cd $SITE_DIR/releases/$CI_JOB_ID && composer install"
    - ssh -p22 $DEPLOY_URL "cd $SITE_DIR/releases/$CI_JOB_ID && php artisan migrate"
    - ssh -p22 $DEPLOY_URL "rm $SITE_DIR/current"
    - ssh -p22 $DEPLOY_URL "ln -s $SITE_DIR/releases/$CI_JOB_ID $SITE_DIR/current"
    - ssh -p22 $DEPLOY_URL "cd $SITE_DIR/current && php artisan cache:clear"
    - ssh -p22 $DEPLOY_URL "cd $SITE_DIR/current && php artisan queue:restart"
    - ssh -p22 $DEPLOY_URL "ls -1dt $SITE_DIR/releases/* | tail -n +6 | xargs rm -rf"
  only:
    - master
